name: Daily KenPom Processor

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install packages
      run:
        Rscript -e 'install.packages(c("dplyr","readr"))'

    - name: Run KenPom processor
      run: Rscript scripts/basketball_data_scrape.R

    - name: Commit updated CSV
      run:
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add basketball_data/kenpom_summary.csv
        git commit -m "Update basketball summary"
        git push
